# Generated by Django 4.0.10 on 2025-04-09 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercontact",
            options={"ordering": ["-created_at"]},
        ),
    ]
